### ISSUE TITLE
License

### ISSUE THREAD

**Issue by znicholls** [znicholls/silicone#6]
@Rlamboll do you or Joeri have any preferences re licenses? If no, I'd suggest GNU Affero General Public License v3.0 for the reasons discussed [here](https://github.com/znicholls/netcdf-scm/issues/2) (in short, gives greatest transparency which I think is what we want with this sort of tool where the assumptions really matter). Alternately, you might want to go a level below and make it less restrictive with BSD-2-Clause.

**Comment by Rlamboll** [comment]
@znicholls I don't have a strong preference, AGPL 3.0 seems good.

**Comment by znicholls** [comment]
Ok cool. Thinking about it more bsd-2 might be safer as I can’t see the
IIASA database switching to agpl 3 anytime soon.
